quiz_data = {
        
"General Knowledge": [
        {"question": "Which of the three banks will be merged with the other two to create India’s third-largest bank?", "options": ["Punjab National Bank", "Indian Bank", "Bank of Baroda", "Dena Bank"], "answer": "Indian Bank"},
        {"question": "What is the name of the weak zone of the earth’s crust?", "options": ["Seismic", "Cosmic", "Formic", "Anaemic"], "answer": "Seismic"},
        {"question": "Where was India’s first national Museum opened?", "options": ["Delhi", "Asia", "Rajasthan", "Mumbai"], "answer": "Mumbai"},
        {"question": "The world’s nation 5G mobile network was launched by which country?", "options": ["Japan", "Homer", "South Korea", "Malaysia"], "answer": "South Korea"},
        {"question": "What is the full form of DRDL?", "options": ["Differential Research and Documentation Laboratory", "Department of Research and Development Laboratory", "Defense Research and Development Laboratory", "None of the above"], "answer": "Department of Research and Development Laboratory"},
       {"question": "What is the hardest natural substance on Earth?", "options": ["Diamond", "Gold", "Iron", "Steel"], "answer": "Diamond"},
        {"question": "Which planet is known as the Red Planet?", "options": ["Mars", "Jupiter", "Saturn", "Venus"], "answer": "Mars"},
        {"question": "What is the most spoken language in the world?", "options": ["Mandarin Chinese", "English", "Spanish", "Hindi"], "answer": "Mandarin Chinese"},
        {"question": "Who painted the Mona Lisa?", "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Claude Monet"], "answer": "Leonardo da Vinci"},
        {"question": "What is the largest mammal in the world?", "options": ["Blue whale", "Elephant", "Giraffe", "Great white shark"], "answer": "Blue whale"},
        {"question": "Which city is known as 'The Big Apple'?", "options": ["New York", "Los Angeles", "Chicago", "San Francisco"], "answer": "New York"},
        {"question": "What is the name of the largest ocean on Earth?", "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "answer": "Pacific Ocean"},
        {"question": "Who was the first person to walk on the moon?", "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], "answer": "Neil Armstrong"},
        {"question": "What is the capital city of Japan?", "options": ["Tokyo", "Osaka", "Kyoto", "Nagoya"], "answer": "Tokyo"},
        {"question": "What element does 'O' represent on the periodic table?", "options": ["Oxygen", "Osmium", "Oganesson", "Omnium"], "answer": "Oxygen"},
        {"question": "Who developed the theory of relativity?", "options": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], "answer": "Albert Einstein"},
        {"question": "Which country is the largest by land area?", "options": ["Russia", "Canada", "China", "United States"], "answer": "Russia"},
        {"question": "What is the most popular social media platform as of 2023?", "options": ["Facebook", "YouTube", "Instagram", "TikTok"], "answer": "Facebook"},
        {"question": "Which vitamin is known as the 'sunshine vitamin'?", "options": ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin E"], "answer": "Vitamin D"},
        {"question": "What is the freezing point of water in Celsius?", "options": ["0°C", "32°C", "100°C", "-1°C"], "answer": "0°C"}
        
    ],
    "Science": [
        {"question": "Which of the following is an organic compound?", "options": ["H2O", "NaCl", "CO2", "C2H6"], "answer": "C2H6"},
        {"question": "Which of the following is a non-metal?", "options": ["Sodium", "Oxygen", "Iron", "Calcium"], "answer": "Oxygen"},
        {"question": "The change in the frequency or wavelength of a wave as it passes from one medium to another is called:", "options": ["Diffraction", "Reflection", "Refraction", "Interference"], "answer": "Refraction"},
        {"question": "A material through which electric current can pass with very little resistance is called a:", "options": ["Conductor", "Insulator", "Semiconductor", "Diode"], "answer": "Conductor"},
        {"question": "Which of the following is NOT a renewable source of energy?", "options": ["Solar energy", "Wind energy", "Fossil fuels", "Hydroelectric energy"], "answer": "Fossil fuels"},
     {"question": "What planet is known as the 'Gas Giant'?", "options": ["Jupiter", "Earth", "Mars", "Venus"], "answer": "Jupiter"},
        {"question": "Which blood cells help fight infections?", "options": ["White blood cells", "Red blood cells", "Platelets", "Plasma cells"], "answer": "White blood cells"},
        {"question": "What force keeps us on the ground?", "options": ["Gravity", "Magnetism", "Friction", "Electromagnetism"], "answer": "Gravity"},
        {"question": "Which element has the atomic number 1?", "options": ["Hydrogen", "Oxygen", "Helium", "Carbon"], "answer": "Hydrogen"},
        {"question": "What organelle is known as the 'powerhouse of the cell'?", "options": ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"], "answer": "Mitochondria"},
        {"question": "What type of animal is a frog?", "options": ["Amphibian", "Reptile", "Mammal", "Bird"], "answer": "Amphibian"},
        {"question": "What is the speed of light?", "options": ["299,792,458 m/s", "3,000,000 m/s", "186,000 m/s", "300,000 km/s"], "answer": "299,792,458 m/s"},
        {"question": "Which planet is closest to the sun?", "options": ["Mercury", "Venus", "Earth", "Mars"], "answer": "Mercury"},
        {"question": "What is the process by which plants make their own food?", "options": ["Photosynthesis", "Respiration", "Digestion", "Osmosis"], "answer": "Photosynthesis"},
        {"question": "What is the main gas found in the Sun?", "options": ["Hydrogen", "Oxygen", "Carbon", "Nitrogen"], "answer": "Hydrogen"},
        {"question": "What is the largest organ in the human body?", "options": ["Skin", "Liver", "Brain", "Heart"], "answer": "Skin"},
        {"question": "What is the pH level of pure water?", "options": ["7", "0", "5", "14"], "answer": "7"},
        {"question": "What part of the cell contains genetic material?", "options": ["Nucleus", "Cytoplasm", "Cell membrane", "Mitochondria"], "answer": "Nucleus"},
        {"question": "What is the boiling point of water in Celsius?", "options": ["100°C", "0°C", "50°C", "75°C"], "answer": "100°C"},
        {"question": "What is the chemical symbol for sodium?", "options": ["Na", "S", "N", "Sa"], "answer": "Na"}
    
    ],
    "Math": [
        {"question": "What is the quadratic formula?", "options": ["x = (-b ± √b² - 4ac) / 2a", "x = (-b ± √b² + 4ac) / 2a", "x = (-b ± 2a√b² - 4ac) / 2a", "x = (-b ± 2a√b² + 4ac) / 2a"], "answer": "x = (-b ± √b² - 4ac) / 2a"},
        {"question": "What is the common difference of the arithmetic progression 3, 7, 11, 15, 19, … ?", "options": ["3", "4", "5", "6"], "answer": "4"},
        {"question": "What is the value of sin 60°?", "options": ["1/2", "√3/2", "1/√2", "√2/2"], "answer": "√3/2"},
        {"question": "What is the area of an equilateral triangle with a side length of 6 cm?", "options": ["9√3 cm²", "18 cm²", "36√3 cm²", "108 cm²"], "answer": "9√3 cm²"},
        {"question": "What is the solution of the system of equations 2x - y = 1 and x + y = 5?", "options": ["x = 2, y = 3", "x = 3, y = 2", "x = 1, y = 4", "x = 4, y = 1"], "answer": "x = 2, y = 3"},
        {"question": "What is the value of cos(0°)?", "options": ["0", "1", "-1", "Undefined"], "answer": "1"},
        {"question": "What is 7 factorial (7!)?", "options": ["5040", "40320", "120", "720"], "answer": "5040"},
        {"question": "What is the slope formula?", "options": ["(y₂ - y₁) / (x₂ - x₁)", "y = mx + b", "(x₂ - x₁) / (y₂ - y₁)", "y = m(x - x₁) + b"], "answer": "(y₂ - y₁) / (x₂ - x₁)"},
        {"question": "What is the formula for the volume of a sphere?", "options": ["(4/3)πr³", "2πr³", "πr²h", "πr³"], "answer": "(4/3)πr³"},
        {"question": "What is the median of the data set {3, 7, 9, 15, 21}?", "options": ["9", "7", "15", "12"], "answer": "9"},
        {"question": "What is the sum of the infinite geometric series 1 + 1/2 + 1/4 + 1/8 + … ?", "options": ["2", "1", "1.5", "Infinity"], "answer": "2"},
        {"question": "What is the formula for compound interest?", "options": ["A = P(1 + r/n)^(nt)", "A = P(1 + rt)", "A = Prt", "A = P + rt"], "answer": "A = P(1 + r/n)^(nt)"},
        {"question": "What is the value of e (Euler's number) approximately?", "options": ["2.718", "3.141", "1.618", "2.5"], "answer": "2.718"},
        {"question": "What is the formula for the perimeter of a rectangle?", "options": ["2(l + w)", "l + w", "lw", "2lw"], "answer": "2(l + w)"},
        {"question": "What is the range of the function f(x) = x²?", "options": ["[0, ∞)", "(-∞, ∞)", "(0, ∞)", "[1, ∞)"], "answer": "[0, ∞)"},
        {"question": "What is the common ratio of the geometric sequence 2, 6, 18, 54, … ?", "options": ["2", "3", "4", "6"], "answer": "3"},
        {"question": "What is the formula for the circumference of a circle?", "options": ["2πr", "πr²", "πd", "r²"], "answer": "2πr"},
        {"question": "What is the midpoint formula?", "options": ["((x₁ + x₂)/2, (y₁ + y₂)/2)", "(x₂ - x₁, y₂ - y₁)", "y = mx + b", "y₂ - y₁ / x₂ - x₁"], "answer": "((x₁ + x₂)/2, (y₁ + y₂)/2)"},
        {"question": "What is the value of i² in complex numbers?", "options": ["-1", "1", "0", "Undefined"], "answer": "-1"},
        {"question": "What is the solution to the equation x² - 5x + 6 = 0?", "options": ["x = 2, x = 3", "x = -2, x = 3", "x = 2, x = -3", "x = -2, x = -3"], "answer": "x = 2, x = 3"}
  
    ],
    "History": [
        
        {"question": "Who was the first President of the United States?", "options": ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], "answer": "George Washington"},
        {"question": "What year did World War II end?", "options": ["1945", "1941", "1939", "1950"], "answer": "1945"},
        {"question": "Who was the primary author of the Declaration of Independence?", "options": ["Thomas Jefferson", "Benjamin Franklin", "John Adams", "James Madison"], "answer": "Thomas Jefferson"},
        {"question": "In which country did the Industrial Revolution begin?", "options": ["United Kingdom", "United States", "Germany", "France"], "answer": "United Kingdom"},
        {"question": "Which ancient civilization built the Pyramids?", "options": ["Egyptians", "Romans", "Greeks", "Mesopotamians"], "answer": "Egyptians"},
        {"question": "Who was known as the 'Maid of Orléans'?", "options": ["Joan of Arc", "Marie Antoinette", "Catherine the Great", "Cleopatra"], "answer": "Joan of Arc"},
        {"question": "What year did the Berlin Wall fall?", "options": ["1989", "1979", "1991", "1961"], "answer": "1989"},
        {"question": "Who was the leader of the Soviet Union during World War II?", "options": ["Joseph Stalin", "Vladimir Lenin", "Nikita Khrushchev", "Mikhail Gorbachev"], "answer": "Joseph Stalin"},
        {"question": "What was the capital of the Byzantine Empire?", "options": ["Constantinople", "Athens", "Rome", "Alexandria"], "answer": "Constantinople"},
        {"question": "What was the name of the ship that brought the Pilgrims to America in 1620?", "options": ["Mayflower", "Santa Maria", "Beagle", "Endeavour"], "answer": "Mayflower"},
        {"question": "Who was the British queen with the longest reign before Queen Elizabeth II?", "options": ["Queen Victoria", "Queen Anne", "Queen Mary I", "Queen Elizabeth I"], "answer": "Queen Victoria"},
        {"question": "Who was the first emperor of Rome?", "options": ["Augustus", "Julius Caesar", "Nero", "Tiberius"], "answer": "Augustus"},
        {"question": "What was the main religion of the Mughal Empire?", "options": ["Islam", "Hinduism", "Buddhism", "Christianity"], "answer": "Islam"},
        {"question": "Who was the famous Greek philosopher sentenced to death by drinking poison?", "options": ["Socrates", "Plato", "Aristotle", "Pythagoras"], "answer": "Socrates"},
        {"question": "What was the name of the alliance between Germany, Italy, and Japan in World War II?", "options": ["Axis Powers", "Allied Powers", "Central Powers", "Triple Entente"], "answer": "Axis Powers"},
        {"question": "Which empire was ruled by Genghis Khan?", "options": ["Mongol Empire", "Roman Empire", "Ottoman Empire", "Persian Empire"], "answer": "Mongol Empire"},
        {"question": "Who wrote the 'I Have a Dream' speech?", "options": ["Martin Luther King Jr.", "Malcolm X", "Rosa Parks", "Frederick Douglass"], "answer": "Martin Luther King Jr."},
        {"question": "In which year did the American Civil War start?", "options": ["1861", "1865", "1776", "1812"], "answer": "1861"},
        {"question": "Who was the famous queen of ancient Egypt who had alliances with Julius Caesar and Mark Antony?", "options": ["Cleopatra", "Nefertiti", "Hatshepsut", "Ankhesenamun"], "answer": "Cleopatra"},
        {"question": "What was the major outcome of the Treaty of Versailles?", "options": ["End of World War I", "Start of World War II", "End of the American Civil War", "End of the Cold War"], "answer": "End of World War I"}


    ],
      "Geography": [
        {"question": "What is the largest continent by land area?", "options": ["Asia", "Africa", "North America", "Europe"], "answer": "Asia"},
        {"question": "Which is the longest river in the world?", "options": ["Nile", "Amazon", "Yangtze", "Mississippi"], "answer": "Nile"},
        {"question": "What is the capital city of Australia?", "options": ["Canberra", "Sydney", "Melbourne", "Perth"], "answer": "Canberra"},
        {"question": "Which country has the largest population?", "options": ["China", "India", "United States", "Indonesia"], "answer": "China"},
        {"question": "Which ocean is the largest by surface area?", "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "answer": "Pacific Ocean"},
        {"question": "What is the smallest country in the world by area?", "options": ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], "answer": "Vatican City"},
        {"question": "Which desert is the largest hot desert in the world?", "options": ["Sahara", "Arabian", "Gobi", "Kalahari"], "answer": "Sahara"},
        {"question": "Mount Everest is located in which mountain range?", "options": ["Himalayas", "Andes", "Rockies", "Alps"], "answer": "Himalayas"},
        {"question": "Which country is known as the Land of the Rising Sun?", "options": ["Japan", "China", "South Korea", "Thailand"], "answer": "Japan"},
        {"question": "What is the longest mountain range in the world?", "options": ["Andes", "Rocky Mountains", "Himalayas", "Alps"], "answer": "Andes"},
        {"question": "Which U.S. state has the longest coastline?", "options": ["Alaska", "California", "Florida", "Texas"], "answer": "Alaska"},
        {"question": "What is the capital of Canada?", "options": ["Ottawa", "Toronto", "Vancouver", "Montreal"], "answer": "Ottawa"},
        {"question": "What is the driest place on Earth?", "options": ["Atacama Desert", "Sahara Desert", "Death Valley", "Gobi Desert"], "answer": "Atacama Desert"},
        {"question": "Which country has the most time zones?", "options": ["France", "Russia", "United States", "China"], "answer": "France"},
        {"question": "Which African country is the largest by area?", "options": ["Algeria", "Sudan", "Congo", "Egypt"], "answer": "Algeria"},
        {"question": "What is the largest lake in the world by surface area?", "options": ["Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"], "answer": "Caspian Sea"},
        {"question": "Which U.S. state has the most volcanoes?", "options": ["Alaska", "Hawaii", "California", "Washington"], "answer": "Alaska"},
        {"question": "What is the deepest point in the world's oceans?", "options": ["Mariana Trench", "Java Trench", "Puerto Rico Trench", "Tonga Trench"], "answer": "Mariana Trench"},
        {"question": "Which country has the highest number of islands?", "options": ["Sweden", "Indonesia", "Philippines", "Greece"], "answer": "Sweden"},
        {"question": "What is the capital city of Brazil?", "options": ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"], "answer": "Brasília"}
      ],
      "Literature": [
        {"question": "Who wrote 'Pride and Prejudice'?", "options": ["Jane Austen", "Charlotte Brontë", "Emily Dickinson", "George Eliot"], "answer": "Jane Austen"},
        {"question": "Who is the author of '1984'?", "options": ["George Orwell", "Aldous Huxley", "Ray Bradbury", "J.D. Salinger"], "answer": "George Orwell"},
        {"question": "What is the title of the first Harry Potter book?", "options": ["Harry Potter and the Philosopher's Stone", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Goblet of Fire", "Harry Potter and the Order of the Phoenix"], "answer": "Harry Potter and the Philosopher's Stone"},
        {"question": "Who wrote the epic poem 'The Odyssey'?", "options": ["Homer", "Virgil", "Sophocles", "Plato"], "answer": "Homer"},
        {"question": "Which playwright wrote 'Hamlet'?", "options": ["William Shakespeare", "Christopher Marlowe", "Ben Jonson", "Thomas Middleton"], "answer": "William Shakespeare"},
        {"question": "What is the name of Sherlock Holmes's assistant?", "options": ["Dr. Watson", "Inspector Lestrade", "Mycroft Holmes", "Professor Moriarty"], "answer": "Dr. Watson"},
        {"question": "Who is the author of 'To Kill a Mockingbird'?", "options": ["Harper Lee", "Ernest Hemingway", "John Steinbeck", "F. Scott Fitzgerald"], "answer": "Harper Lee"},
        {"question": "In which country is 'The Divine Comedy' set?", "options": ["Italy", "Greece", "France", "Egypt"], "answer": "Italy"},
        {"question": "Who wrote 'The Catcher in the Rye'?", "options": ["J.D. Salinger", "John Steinbeck", "Ernest Hemingway", "Mark Twain"], "answer": "J.D. Salinger"},
        {"question": "Which novel begins with the line 'Call me Ishmael'?", "options": ["Moby-Dick", "Great Expectations", "The Scarlet Letter", "The Old Man and the Sea"], "answer": "Moby-Dick"},
        {"question": "Who is the author of 'The Great Gatsby'?", "options": ["F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "Mark Twain"], "answer": "F. Scott Fitzgerald"},
        {"question": "Who wrote the play 'A Streetcar Named Desire'?", "options": ["Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "Samuel Beckett"], "answer": "Tennessee Williams"},
        {"question": "What is the name of the main character in 'The Catcher in the Rye'?", "options": ["Holden Caulfield", "Jay Gatsby", "Nick Carraway", "Tom Joad"], "answer": "Holden Caulfield"},
        {"question": "Who wrote 'The Picture of Dorian Gray'?", "options": ["Oscar Wilde", "Charles Dickens", "Virginia Woolf", "George Eliot"], "answer": "Oscar Wilde"},
        {"question": "Which Russian author wrote 'War and Peace'?", "options": ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"], "answer": "Leo Tolstoy"},
        {"question": "In 'Romeo and Juliet', what is Juliet's last name?", "options": ["Capulet", "Montague", "Paris", "Verona"], "answer": "Capulet"},
        {"question": "Who wrote 'The Road Not Taken'?", "options": ["Robert Frost", "Emily Dickinson", "Walt Whitman", "T.S. Eliot"], "answer": "Robert Frost"},
        {"question": "Who wrote the dystopian novel 'Brave New World'?", "options": ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Philip K. Dick"], "answer": "Aldous Huxley"},
        {"question": "In which novel would you find the characters Pip and Miss Havisham?", "options": ["Great Expectations", "Oliver Twist", "David Copperfield", "A Tale of Two Cities"], "answer": "Great Expectations"},
        {"question": "Which book features a character named Atticus Finch?", "options": ["To Kill a Mockingbird", "Pride and Prejudice", "Of Mice and Men", "The Grapes of Wrath"], "answer": "To Kill a Mockingbird"}
    ]
}